---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,fr-fr
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Keystone文档
    url: "/index.html"
  - title: 入门
    entries:
    - title: 了解Keystone
      url: "/concepts/overview.html"
    - title: Keystone支持的存储容量
      url: "/concepts/supported-storage-capacity.html"
    - title: Keystone服务的指标和定义
      url: "/concepts/metrics.html"
    - title: Keystone中支持的存储类型
      url: "/concepts/supported-storage-services.html"
    - title: Keystone中的服务级别
      url: "/concepts/service-levels.html"
    - title: 附加服务
      entries:
      - title: 数据分层
        url: "/concepts/data-tiering.html"
      - title: 高级数据保护
        url: "/concepts/adp.html"
      - title: U.S.公民支持(USCS)
        url: "/concepts/uscs.html"
      - title: 不可退回的非易失性组件以及SnapLock 合规性
        url: "/concepts/nrnvc.html"
      - title: Keystone和Equinix
        url: "/concepts/equinix.html"
  - title: 有关服务级别的更多信息
    entries:
    - title: Quality of service
      url: "/concepts/qos.html"
    - title: 服务级别的容量要求
      url: "/concepts/capacity-requirements.html"
  - title: 计费
    entries:
    - title: Keystone定价
      url: "/concepts/pricing.html"
    - title: 根据已提交容量计费
      url: "/concepts/committed-capacity-billing.html"
    - title: 根据已用容量进行计量
      url: "/concepts/consumed-capacity-billing.html"
    - title: 按突发消耗计费
      url: "/concepts/burst-consumption-billing.html"
    - title: 根据其他卷类型计费
      url: "/concepts/misc-volume-billing.html"
    - title: 计费计划
      url: "/concepts/billing-schedules.html"
  - title: 合作伙伴和客户运营的环境
    url: "/concepts/operational-models.html"
  - title: Keystone基础架构
    entries:
    - title: 基础架构详细信息
      url: "/concepts/infra.html"
    - title: 组件
      url: "/concepts/components.html"
    - title: 将OpsRamp用作监控应用程序
      url: "/concepts/opsramp.html"
    - title: 数据流
      url: "/concepts/data-flow.html"
  - title: NetApp全球服务支持中心
    url: "/concepts/gssc.html"
  - title: 利用Keystone服务完成更多任务
    entries:
    - title: Keystone和Cloud Manager
      url: "/integrations/keystone-cm.html"
    - title: Keystone和Active IQ 数字顾问
      url: "/integrations/keystone-aiq.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 什么是 NetApp Keystone ？
      url: "/concepts/overview.html"
    - title: 度量单位是多少？
      url: "/concepts/metrics.html"
    - title: 支持的基础存储是什么？
      url: "/concepts/supported-storage-services.html"
    - title: 什么是数据分层？
      url: "/concepts/data-tiering.html"
    - title: 我的Keystone数据是否受到保护？
      url: "/concepts/adp.html"
  - title: Keystone中的服务级别
    links:
    - title: Keystone服务级别
      url: "/concepts/service-levels.html"
    - title: 服务质量(QoS)
      url: "/concepts/qos.html"
    - title: 服务级别的容量要求
      url: "/concepts/capacity-requirements.html"
    - title: 如何查看我的消费数据？
      url: "/integrations/keystone-aiq.html"
  - title: Keystone定价
    links:
    - title: 了解Keystone计费
      url: "/concepts/pricing.html"
    - title: 我的计费计划
      url: "/concepts/billing-schedules.html"
    - title: 根据已提交容量计费
      url: "/concepts/committed-capacity-billing.html"
    - title: 根据已用容量进行计量
      url: "/concepts/consumed-capacity-billing.html"
    - title: 如果我消耗的容量超过承诺的容量、会发生什么情况？
      url: "/concepts/burst-consumption-billing.html"
  - title: 利用Keystone服务完成更多任务
    links:
    - title: 了解您的支持团队(Keystone GSSC)
      url: "/concepts/gssc.html"
    - title: Keystone和Cloud Manager
      url: "/integrations/keystone-cm.html"
    - title: Keystone和Active IQ 数字顾问
      url: "/integrations/keystone-aiq.html"
    - title: 美国公民支持
      url: "/concepts/uscs.html"
  - title: 了解更多信息
    links:
    - title: Keystone Flex 订阅
      url: https://docs.netapp.com/us-en/keystone/
    - title: Active IQ Digital Advisor
      url: https://docs.netapp.com/us-en/active-iq/index.html
    - title: Cloud Manager
      url: https://docs.netapp.com/us-en/cloud-manager-family/
    - title: Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/
