---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Keystone文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: Keystone STaaS的新增功能
      url: "/release-notes/whats-new.html"
    - title: 已修复的问题
      url: "/release-notes/fixed-issues.html"
    - title: 已知限制
      url: "/release-notes/known-limitations.html"
    - title: 已知问题
      url: "/release-notes/known-issues.html"
  - title: 欢迎使用Keystone
    url: "/concepts/overview.html"
  - title: 设置和配置Keystone
    entries:
    - title: 什么是Keystone收集器
      url: "/installation/installation-overview.html"
    - title: 准备系统
      entries:
      - title: VMware vSphere 要求
        url: "/installation/vapp-prereqs.html"
      - title: Linux要求
        url: "/installation/linux-prereqs.html"
      - title: ONTAP和StorageGRID要求
        url: "/installation/addl-req.html"
    - title: 安装Keystone收集器
      entries:
      - title: VMware vSphere部署
        url: "/installation/vapp-installation.html"
      - title: Linux安装
        url: "/installation/linux-installation.html"
      - title: 自动完整性验证
        url: "/installation/validation.html"
    - title: 配置Keystone收集器
      url: "/installation/configuration.html"
    - title: 监控系统运行状况
      url: "/installation/monitor-health.html"
    - title: 升级Keystone收集器
      url: "/installation/upgrade.html"
    - title: 为Keystone配置AutoSupport
      url: "/installation/asup-config.html"
    - title: 收集用于计费的数据
      url: "/installation/data-collection.html"
  - title: 查看Keystone信息板并管理订阅
    entries:
    - title: 在Active IQ数字顾问上查看Keystone信息板
      entries:
      - title: Keystone和Digital Advisor信息板
        url: "/integrations/keystone-aiq.html"
      - title: 查看消耗详细信息并生成报告
        url: "/integrations/aiq-keystone-details.html"
      - title: 订阅选项卡
        url: "/integrations/subscriptions-tab.html"
      - title: 当前使用量选项卡
        url: "/integrations/current-usage-tab.html"
      - title: 容量趋势选项卡
        url: "/integrations/capacity-trend-tab.html"
      - title: 卷和对象选项卡
        url: "/integrations/volumes-objects-tab.html"
      - title: 性能选项卡
        url: "/integrations/performance-tab.html"
      - title: 资产选项卡
        url: "/integrations/assets-tab.html"
    - title: 从BlueXP管理Keystone订阅
      url: "/integrations/keystone-cm.html"
  - title: 了解Keystone
    entries:
    - title: 支持的存储容量
      url: "/concepts/supported-storage-capacity.html"
    - title: 指标和定义
      url: "/concepts/metrics.html"
    - title: Keystone支持的存储
      url: "/concepts/supported-storage-services.html"
    - title: Keystone中的服务级别
      url: "/concepts/service-levels.html"
    - title: 附加服务
      entries:
      - title: Keystone STaaS中的附加服务
        url: "/concepts/add-on.html"
      - title: 数据分层
        url: "/concepts/data-tiering.html"
      - title: 高级数据保护
        url: "/concepts/adp.html"
      - title: U.S.公民支持(USCS)
        url: "/concepts/uscs.html"
      - title: 不可退回的非易失性组件以及SnapLock 合规性
        url: "/concepts/nrnvc.html"
      - title: Keystone和Equinix
        url: "/concepts/equinix.html"
    - title: Keystone订阅服务版本1
      url: "/subscription-services-v1.html"
  - title: 有关服务级别的更多信息
    entries:
    - title: Quality of service
      url: "/concepts/qos.html"
    - title: 服务级别的容量要求
      url: "/concepts/capacity-requirements.html"
  - title: 计费
    entries:
    - title: Keystone定价
      url: "/concepts/pricing.html"
    - title: 根据已提交容量计费
      url: "/concepts/committed-capacity-billing.html"
    - title: 根据已用容量进行计量
      url: "/concepts/consumed-capacity-billing.html"
    - title: 按突发消耗计费
      url: "/concepts/burst-consumption-billing.html"
    - title: 根据其他卷类型计费
      url: "/concepts/misc-volume-billing.html"
    - title: 计费计划
      url: "/concepts/billing-schedules.html"
  - title: 合作伙伴和客户运营的环境
    url: "/concepts/operational-models.html"
  - title: Keystone基础架构
    entries:
    - title: 基础架构详细信息
      url: "/concepts/infra.html"
    - title: 组件
      url: "/concepts/components.html"
    - title: 数据流
      url: "/concepts/data-flow.html"
  - title: NetApp全球服务支持中心
    url: "/concepts/gssc.html"
  - title: 法律声明
    url: "/legal-notices.html"
