---
settings:
  name: Keystone
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '3.0'
    url: "/keystone-staas"
  - version-number: '2.0'
    url: "/keystone-staas-2"
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: Keystone文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: Keystone STaaS的新增功能
      url: "/whats-new.html"
    - title: 已修复的问题
      url: "/release-notes/fixed-issues.html"
    - title: 已知问题
      url: "/release-notes/known-issues.html"
    - title: 已知限制
      url: "/release-notes/known-limitations.html"
  - title: 入门
    entries:
    - title: 了解 Keystone STaaS
      url: "/concepts/overview.html"
    - title: Keystone基础架构
      url: "/concepts/infra.html"
    - title: Keystone收集器
      url: "/installation/installation-overview.html"
    - title: 组件
      url: "/concepts/components.html"
    - title: 数据流
      url: "/concepts/data-flow.html"
    - title: 操作模式
      url: "/concepts/operational-models.html"
  - title: 设置和配置Keystone
    entries:
    - title: 要求
      entries:
      - title: 虚拟基础架构
        url: "/installation/vapp-prereqs.html"
      - title: Linux
        url: "/installation/linux-prereqs.html"
      - title: ONTAP和StorageGRID
        url: "/installation/addl-req.html"
    - title: 安装Keystone收集器
      entries:
      - title: 在VMware vSphere上部署
        url: "/installation/vapp-installation.html"
      - title: 在Linux上安装
        url: "/installation/linux-installation.html"
      - title: Keystone软件的自动验证
        url: "/installation/validation.html"
    - title: 配置Keystone收集器
      url: "/installation/configuration.html"
    - title: 安装ITOM收集器
      entries:
      - title: 准备安装
        url: "/installation/itom-prereqs.html"
      - title: 在Linux上安装
        url: "/installation/install-itom-linux.html"
      - title: 在Windows上安装
        url: "/installation/install-itom-windows.html"
    - title: 配置 AutoSupport
      url: "/installation/asup-config.html"
    - title: 监控和升级
      entries:
      - title: 监控Keystone收集器运行状况
        url: "/installation/monitor-health.html"
      - title: 升级Keystone收集器
        url: "/installation/upgrade.html"
    - title: Keystone收集器安全性
      url: "/installation/security.html"
    - title: 收集用于计费的数据
      url: "/installation/data-collection.html"
    - title: Keystone处于专用模式
      entries:
      - title: 概述
        url: "/dark-sites/overview.html"
      - title: 准备安装
        url: "/dark-sites/requirements.html"
      - title: 安装Keystone收集器
        url: "/dark-sites/install-collector.html"
      - title: 配置Keystone收集器
        url: "/dark-sites/configure-collector.html"
      - title: 监控Keystone收集器运行状况
        url: "/dark-sites/monitor.html"
  - title: 管理和监控 Keystone 订阅
    entries:
    - title: 了解 Keystone 仪表板
      entries:
      - title: 了解 Keystone 仪表板
        url: "/integrations/dashboard-overview.html"
      - title: 开始使用 Keystone 仪表板
        url: "/integrations/dashboard-access.html"
      - title: NetApp控制台中的Keystone仪表板
        url: "/integrations/keystone-console.html"
      - title: Digital Advisor 中的 Keystone 仪表板
        url: "/integrations/keystone-aiq.html"
      - title: 搜索数据、生成报告和查看警报
        url: "/integrations/options.html"
    - title: 查看订阅洞察
      entries:
      - title: 查看您的订阅详情
        url: "/integrations/subscriptions-tab.html"
      - title: 查看您当前的消费详情
        url: "/integrations/current-usage-tab.html"
      - title: 查看消费趋势
        url: "/integrations/consumption-tab.html"
      - title: 查看您的订阅时间表
        url: "/integrations/subscription-timeline.html"
    - title: 查看资产
      entries:
      - title: 查看与订阅相关的资产
        url: "/integrations/assets-tab.html"
      - title: 查看多个订阅中的资产
        url: "/integrations/assets.html"
    - title: 查看和管理警报和监视器
      entries:
      - title: 查看和管理警报
        url: "/integrations/monitoring-alerts.html"
      - title: 查看和创建警报监视器
        url: "/integrations/monitoring-alert-monitors.html"
    - title: 修改您的订阅
      url: "/integrations/modify-subscription.html"
    - title: 查看您的服务请求
      url: "/integrations/administration-tab.html"
    - title: 查看卷和对象存储详细信息
      url: "/integrations/volumes-objects-tab.html"
    - title: 查看性能指标
      url: "/integrations/performance-tab.html"
  - title: 概念
    entries:
    - title: Keystone STaaS服务
      entries:
      - title: 指标和定义
        url: "/concepts/metrics.html"
      - title: 支持的存储
        url: "/concepts/supported-storage-services.html"
      - title: 支持的容量
        url: "/concepts/supported-storage-capacity.html"
      - title: 绩效服务水平
        url: "/concepts/service-levels.html"
      - title: 性能服务级别的容量要求
        url: "/concepts/capacity-requirements.html"
    - title: 了解附加服务
      entries:
      - title: 突发容量选项
        url: "/concepts/burst-capacity.html"
      - title: 数据基础架构洞察力
        url: "/concepts/data-infra-insights.html"
      - title: 数据分层
        url: "/concepts/data-tiering.html"
      - title: 非可退还、非易失性组件、符合SnapLock标准
        url: "/concepts/nrnvc.html"
      - title: 美国受保护支持(USPS)
        url: "/concepts/usps.html"
    - title: 了解Keystone STaaS SLO
      entries:
      - title: 可用性
        url: "/concepts/sla-availability.html"
      - title: 性能
        url: "/concepts/sla-performance.html"
      - title: 可持续性
        url: "/concepts/sla-sustainability.html"
      - title: 勒索软件恢复担保
        url: "/concepts/sla-ransomware.html"
    - title: 了解计费方式
      entries:
      - title: Keystone定价
        url: "/concepts/pricing.html"
      - title: 根据已提交容量计费
        url: "/concepts/committed-capacity-billing.html"
      - title: 根据已用容量进行计量
        url: "/concepts/consumed-capacity-billing.html"
      - title: 按突发消耗计费
        url: "/concepts/burst-consumption-billing.html"
      - title: 针对特定容量配置的计费
        url: "/concepts/misc-volume-billing.html"
      - title: 计费计划
        url: "/concepts/billing-schedules.html"
  - title: 从Digital Advisor REST API访问Keystone
    entries:
    - title: 开始使用Digital Advisor REST API检索Keystone数据
      url: "/rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html"
    - title: 生成刷新和访问令牌
      url: "/rest-api/generate-tokens.html"
    - title: 使用Digital Advisor REST API获取所有客户的列表
      url: "/rest-api/get-customer-list.html"
    - title: 使用Digital Advisor REST API获取客户订阅
      url: "/rest-api/get-customer-subscriptions.html"
    - title: 使用Digital Advisor REST API获取客户使用情况详细信息
      url: "/rest-api/get-customer-consumption.html"
  - title: Keystone订阅服务版本1
    url: "/subscription-services-v1.html"
  - title: 获取Keystone帮助
    url: "/concepts/support-services.html"
  - title: 法律声明
    url: "/legal-notices.html"
