---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Global Services Support Center, GSSC, Keystone support 
summary: NetApp全球服务支持中心GSSC 
---
= NetApp全球服务支持中心
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone 服务可利用NetApp全球服务和支持中心(GSSC)、NetApp Keystone 成功经理和NetApp Keystone 服务交付经理来运行。



== NetApp 全球服务和支持中心（ GSSC ）

NetApp 为 NetApp Keystone 客户远程提供运营服务。这些服务涵盖存储管理活动中的一系列操作准则。这些服务包括资产和配置管理、容量和性能管理、变更管理、事件、意外事件和问题管理、服务请求履行和报告。NetApp会根据需要展示控制状态和支持证据。



== 追加信息和支持联系人

NetApp全球服务和支持中心(GSSC)团队主要为NetApp Keystone 客户提供服务支持。您可以使用以下信息联系支持团队。

* 全球服务联系人：https://www.netapp.com/us/contact-us/support.aspx[]
* 如果您有待处理案例/服务单需要上报、请发送电子邮件至以下地址之一：keystone.services@netapp.com keystone.escalations@netapp.com
* NetApp使用基于云的远程网关解决方案 OpsRamp主动监控和连接到NetApp Keystone 环境以进行故障排除。有关 OpsRamp 的信息，请参见 https://www.opsramp.com/#[]。



NOTE: 在合作伙伴运营的模式中、租户和子租户的服务请求将分配给合作伙伴的服务台。合作伙伴的支持工具可能已与 OpsRamp 和 GSSC 应用程序集成。只有 L3 问题才会通过 GSSC 上报给 NetApp 。

有关详细信息，请参见

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* NetApp 产品文档https://docs.netapp.com["https://docs.netapp.com"^]




== GSSC监控

NetApp全球服务和支持中心(GSSC)可监控您的产品和订阅服务的运行状况、提供远程支持、并与您的Keystone Success Manager合作。监控与相关Keystone订阅订单相关的产品的所有人员均为在美国运营的美国公民土壤。

Keystone成功经理是一名美国员工美国公民土壤。这些职责在您的NetApp Keystone 协议中进行了规定。

有关信息，请参见 link:../concepts/uscs.html["U.S.公民支持(USCS)"]。
