---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability 
summary: Keystone服务的指标计算和定义 
---
= Keystone服务中使用的指标和定义
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone (Keystone) STaaS服务使用以下术语和定义来衡量指标：

* 容量测量单位：GIB、TiB和PIB
* IO密度：IOPS/TiB：根据工作负载占用的总空间、每秒处理的输入/输出操作数(以太字节为单位)。
* 服务可用性
* 持久准确的数据访问
* 延迟和速度




== 衡量指标

* *以千字节(GiB)、太字节(TiB)和对等字节(PIB)为单位的容量测量*：以1024为基数(1 GiB = 1024^3^字节、1 TiB = 1024^4^字节、1 PiB = 1024^5^字节)测量数据存储容量。
* IOPS/TiB*中的*操作计数器图表：应用程序请求的每秒协议操作数除以工作负载使用的卷大小。
* *可用性*：以服务成功响应的I/O请求数的百分比除以对服务发出的I/O请求总数。这在一个月内的服务划分时进行衡量、不包括计划内服务停机或客户提供的设施、网络或其他服务不可用。
* *持久性*：在不影响保真度的情况下访问数据的百分比、不包括客户导致的删除或损坏。
* *延迟*：从客户端收到的I/O请求的服务时间、以服务划分(存储控制器I/O端口)为单位。




=== 吞吐量性能指标

吞吐量性能指标仅适用于基于以下各项的文件和块服务：

* 32 KB块大小
* 70%读取/ 30%写入I/O混合




=== IO密度的变化

根据以下因素、以IOPS/TiB和/或MBPS/TiB计算的IO密度会有所不同：

* 工作负载特征
* 延迟、不包括以下内容：
+
** 应用程序延迟
** 主机延迟
** 在控制器端口之间传输数据时客户网络出现延迟
** 对于FabricPool 、与向对象存储传输数据相关的开销延迟
** QoS自动应用的延迟、以使IO保持在服务级别上限内


* 计入已用容量的用户和Snapshot副本数据
* 在每个ONTAP 卷上分配的绝对最小IOPS、与卷中的数据量无关：
+
** 至高：1、000次IOPS
** 高级：500 IOPS
** 性能、标准和价值：75 IOPS


* 使用高级数据保护附加服务时、目标延迟仅适用于从本地存储处理IO请求。




=== 卷AQO

每个ONTAP 卷都应应用适用的自适应服务质量(AQoS)策略。否则、未应用AQO策略的每个卷中的容量将按最高服务级别的速率计费。
