---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3 
summary: NetApp Keystone STaaS服务使用多个术语来衡量指标。在使用 Keystone 服务第 3 版时，您可能希望了解有关这些术语的更多信息。 
---
= Keystone中使用的指标和定义
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS服务使用多个术语来衡量指标。在使用 Keystone 版本 3 (v3) 时，您可能想要了解有关这些术语的更多信息。

Keystone STaaS服务使用以下术语和定义来衡量指标：

* 容量测量单位：GIB、TiB和PIB
* IOPS：每秒处理的输入/输出操作数。
* 服务可用性
* 持久准确的数据访问
* 延迟和速度




== 衡量指标

* *以千字节(GiB)、太字节(TiB)和对等字节(PIB)为单位的容量测量*：以1024为基数(1 GiB = 1024^3^字节、1 TiB = 1024^4^字节、1 PiB = 1024^5^字节)测量数据存储容量。
* *IOPS 中的操作计数器图表*：应用程序请求的每秒协议操作数。
* *可用性*：以服务成功响应的I/O请求数的百分比除以对服务发出的I/O请求总数。这在一个月内的服务划分时进行衡量、不包括计划内服务停机或客户提供的设施、网络或其他服务不可用。
* *持久性*：在不影响保真度的情况下访问数据的百分比、不包括客户导致的删除或损坏。
* *延迟*：从客户端收到的I/O请求的服务时间、以服务划分(存储控制器I/O端口)为单位。




=== 性能指标

以下性能指标适用于统一和块优化服务：

*统一服务：*

* *IOPS*：对于带有 NFS 的 ONTAP 9.16.1，每个性能级别实例支持随机访问，读取率为 70%，写入率为 30%，块大小为 8 KB，延迟为 1 毫秒（标准为 4 毫秒）。
* *吞吐量*：对于带有 NFS 的 ONTAP 9.16.1，每个性能级别实例都支持 100% 读取和 32 KB 块大小的顺序访问。


*阻止优化服务：*

* *IOPS*：对于带有 FCP 的 ONTAP 9.16.1，每个性能级别实例支持读取率为 70%、写入率为 30%、块大小为 8 KB 且延迟为 1 毫秒的随机访问。
* *吞吐量*：对于带有 FCP 的 ONTAP 9.16.1，每个性能级别实例都支持 100% 读取和 64 KB 块大小的顺序访问。

