---
sidebar: sidebar 
permalink: concepts/pricing-v2.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone提供按需购买模式、可满足您灵活且可扩展的消费需求。 
---
= Keystone定价
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 按使用量付费订阅服务提供灵活且可扩展的消费，并为您的存储需求提供可预测的预付定价。

Keystone 版本 2 (v2) 为您提供以下计费功能：

* 您可以根据已提交的 IOPS 和延迟容量付费，以满足各种工作负载需求。不同的性能服务层—极高、高级、性能、标准、价值、 通过和对象、您可以根据所购买的服务级别管理存储。
* 它可以为已提交容量提供可预测的计费，并按使用情况为可变（突发）容量使用量付费。
* 您可以为硬件，核心操作系统选择捆绑包价格，并以每 TiB 价格获得支持。对于每种存储类型，文件，块，对象或云存储服务，您都有一张发票。
* 您可以选择灵活的服务期限和付款方式，例如按月、按季度或按年。


Keystone计费基于已提交容量和可变突发消耗量。

有关Keystone中支持的不同容量的信息、请参见 link:../concepts/supported-storage-capacity.html["Keystone支持的存储容量"]。

* 相关信息 *

* link:../concepts/committed-capacity-billing-v2.html["根据已提交容量计费"]
* link:../concepts/consumed-capacity-billing-v2.html["根据已用容量进行计量"]
* link:../concepts/burst-consumption-billing-v2.html["按突发消耗计费"]
* link:../concepts/misc-volume-billing-v2.html["根据其他卷类型计费"]
* link:../concepts/billing-schedules-v2.html["计费计划"]

