---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone提供按需购买模式、可满足您灵活且可扩展的消费需求。 
---
= Keystone定价
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 按使用量付费订阅服务提供灵活且可扩展的消费，并为您的存储需求提供可预测的预付定价。

Keystone为您提供以下计费功能：

* 您可以根据已提交的 IOPS 和延迟容量付费，以满足各种工作负载需求。不同的性能服务层级 - Extreme、Premium、Standard、Value、Object 和 Cloud Volumes ONTAP 使您能够根据购买的服务级别管理存储。
* 它可以为已提交容量提供可预测的计费，并按使用情况为可变（突发）容量使用量付费。
* 您可以为硬件，核心操作系统选择捆绑包价格，并以每 TiB 价格获得支持。对于每种存储类型、统一存储、块存储、优化存储、对象存储或云存储服务，您都有一张发票。
* 您可以选择灵活的服务期限和付款方式，例如按月、按季度、按半年或按年。


Keystone计费基于已提交容量和可变突发消耗量。

有关Keystone中支持的不同容量的信息、请参见 link:../concepts/supported-storage-capacity.html["Keystone支持的存储容量"]。

* 相关信息 *

* link:../concepts/committed-capacity-billing.html["根据已提交容量计费"]
* link:../concepts/consumed-capacity-billing.html["根据已用容量进行计量"]
* link:../concepts/burst-consumption-billing.html["按突发消耗计费"]
* link:../concepts/misc-volume-billing.html["根据其他卷类型计费"]
* link:../concepts/billing-schedules.html["计费计划"]

