---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystone的服务质量 
---
= Keystone中的服务质量(QoS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
存储服务质量(QoS)是一项关键技术、可确保应用程序获得一致且可预测的性能。如果没有QoS、某些工作负载(例如用于启动多个系统的工作负载)可能会在一段时间内占用大部分或全部资源、并影响其他工作负载。有关QoS的信息、请参见 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS 概述保证吞吐量"^]。



== 自适应 QoS

Keystone服务使用自适应QoS (AQoS)根据卷大小动态保持IOS/TiB比率。有关AQO策略的信息、请参见 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["关于自适应 QoS"^]。

Keystone为您提供了AQO策略、您可以在集群投入使用后设置这些策略。您应确保所有卷都与系统中已创建并可用的正确AQO策略相关联。

如果ONTAP 卷未应用AQoS策略、则此卷不合规。没有QoS策略的卷是系统优先级列表中最后一个可提供任何可用输入输出操作的卷。但是、如果有任何输入-输出操作可用、则卷可能会占用所有可用的IO。


NOTE: 如果您尚未对卷应用AQoS策略、系统将根据您的订阅按最高服务级别对这些卷进行衡量和收费。这可能会导致意外的突发费用。



== 自适应QoS设置

自适应QoS (AQoS)设置因服务级别而异。

|===


| *策略名称* | * 至尊 * | * 高级版 * | * 性能 * | * 标准 * | * 值 * 


| *预期IOP* | 6,144 | 2 ， 048 | 1,024 | 256 | 64 


| *预期IOPS分配* 5+| 已分配空间 


| *峰值IOP* | 12,288 | 4,096 | 2 ， 048 | 512 | 128. 


| *峰值IOPS分配* 5+| 已用空间 


| * 块大小 * 5+| 32 K 
|===


== 配置自适应QoS策略组

您可以配置自适应QoS (AQoS)策略、以便根据卷大小自动扩展吞吐量上限或下限。并非所有Keystone服务级别都与默认ONTAP QoS策略一致。您可以为其创建自定义QoS策略。要配置策略、您应注意以下事项：

* *策略组名称*：AQO策略组的名称。例如： `Keystone_extreme`。
* * vserver*：Vserver或Storage VM (Storage Virtual Machine)的名称。
* *预期IOP*：系统在有足够的可用系统IOPS时尝试提供的每个卷的每个已分配TiB的最小IOPS数。
* *峰值IOP*：系统在通过延迟注入限制IOPS之前允许卷达到的每个卷的每个已用TiB的最大IOPS数。
* *预期IOPS分配*：此参数用于控制卷可用的预期IOPS是基于卷的已分配大小还是已使用大小。在Keystone中、此值基于已分配的空间。
* *峰值IOPS分配*：此参数用于控制卷可用的峰值IOPS是基于卷的已分配大小还是已使用大小。在Keystone中、此值基于已用空间。
* *绝对最小IOPS*：如果卷大小非常小、并且可能会导致不可接受的IOPS数量、则应用于卷的预期IOPS的最低数量。对于、此值默认为1、000 `Extreme`、500表示 `Premium`和250 `Performance`和75 `Standard` 和 `Value` 服务级别。
+

NOTE: 这不是IOPS密度(例如75 IOPS/TiB)、而是绝对最小IOPS数。



有关IO密度的信息、请参见 link:../concepts/metrics.html["Keystone服务中使用的指标和定义"]。有关AQO策略组的详细信息、请参见 https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["使用自适应 QoS 策略组"^]。



== 自适应QoS策略的设置

以下各节介绍了每个服务级别的自适应QoS (AQoS)策略设置。此处提供的每个服务级别的最小和最大卷大小可为卷提供最佳IOPS和延迟值。如果在这些准则之外创建的卷过多、可能会对这些卷的性能产生负面影响。



=== 至尊服务级别的设置

适用于极致服务级别的设置和命令：

* 命令示例：


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* 最小卷大小：100 GiB、0.1 TiB
* 最大卷大小：10 TiB




=== 高级服务级别的设置

高级服务级别的设置和命令：

* 命令示例：


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* 最小卷大小：500 GiB、0.5 TiB
* 最大卷大小：50 TiB




=== 性能服务级别的设置

性能服务级别的设置和命令：

* 命令示例：


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* 最小卷大小：500 GiB、0.5 TiB
* 最大卷大小：80 TiB




=== 标准服务级别的设置

标准服务级别的设置和命令：

* 命令示例：


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小卷大小：1 TiB
* 最大卷大小：100 TiB




=== 值服务级别的设置

值服务级别的设置和命令：

* 命令示例：


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小卷大小：1 TiB
* 最大卷大小：100 TiB




== 块大小计算

在使用以下设置计算块大小之前、请注意以下几点：

* IOPS/TiB = Mbps/TiB除以(块大小* 1024)
* 块大小以KB/IO为单位
* TIB = 1024 GiB；GiB = 1024 MiB；MIB = 1024 KiB；KiB = 1024字节；根据基数2
* TB = 1000 GB；GB = 1000 MB；MB = 1000 KB；KB = 1000字节；按基数10计算


.块大小计算示例
计算服务级别的吞吐量、例如 `Extreme` 服务级别：

* 最大IOPS：12、288
* 每个I/O的块大小：32 KB
* 最大吞吐量=(12288 * 32 * 1024)/(1024 * 1024)= 384 MBps/ TiB


如果卷包含700 GiB的已用逻辑数据、则可用吞吐量将为：

`m最大吞吐量= 384 * 0.7 = 268.8MBps`
