---
sidebar: sidebar 
permalink: concepts/sla-sustainability.html 
keywords: sustainability, sla, service level agreement, 
summary: 可持续性、SLA、服务级别协议 
---
= Keystone的可持续性SLA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS提供服务级别协议或SLA支持的可持续性服务级别、定义每个服务级别的最大功耗/ TiB、以帮助您规划、监控和实现IT可持续性目标。

您可以从Active IQ数字顾问(也称为数字顾问)信息板上的Keystone小工具中了解与SLA相关的任何问题。



== 可持续性指标

以下指标定义并衡量可持续性：

* 瓦特：ONTAP AFF A系列阵列和连接的SSD磁盘架的每日功耗。
* TIB：以下各项中的较大项：
+
** 服务级别、或的已提交容量和已分配突发容量
** 有效部署容量、假设存储效率系数为2。有关存储效率比率的信息、请参见 https://docs.netapp.com/us-en/active-iq/concept_overview_storage_efficiency.html["了解存储效率"^]。






== 可持续性服务级别

下表总结了可持续性服务级别：极速、高级和性能：

|===


| * 服务级别 * | *SLA标准* | *最小已提交容量* | * 平台 * 


 a| 
极高
| 小于8瓦/ TiB | 200 TiB | AFF A800和AFF A900 


 a| 
高级版
| 小于4瓦/ TiB | 300 TiB | AFF A800和AFF A900 


 a| 
性能
| 小于4瓦/ TiB | 300 TiB | AFF A800和AFF A900 
|===


== 可持续性SLA的资格标准

符合以下标准的Keystone STaaS订阅符合可持续性SLA的条件：

* 标准的非定制Keystone STaaS订阅、具有单一服务级别、按月延期开票。
* 具有以下服务级别的订阅符合条件：极速、高级和性能服务级别。
* 非定制、参考Keystone可持续硬件配置、包括：
+
** ONTAP AFF A系列存储阵列、例如NetApp AFF A900或AFF A800全闪存存储平台。有关信息，请参见 https://www.netapp.com/data-storage/aff-a-series["AFF A-Series"^]。
** 双节点无交换机集群。
不支持com不 同时配置和MetroCluster配置。


* Keystone使用AutoSupport遥测数据和传输机制来收集可持续发展数据。AutoSupport应在所有ONTAP AFF存储阵列上启用并正常运行。有关详细信息，请参见 https://docs.netapp.com/us-en/active-iq/concept_autosupport.html["AutoSupport"^]。
* 存储的数据应达到最低平均存储效率系数2。
* 环境工作环境温度应介于25°C和27°C之间
* 应满足每个服务级别的最小承诺容量要求。




== 可持续性报告

Digital Advisor的SLA选项卡Keystone信息板提供Keystone订阅的可持续发展指标的详细视图。您可以查看指标并生成报告、以供将来分析和操作使用。

有关Keystone信息板和报告的详细信息、请参见 link:../integrations/aiq-keystone-details.html["Keystone订阅信息板和报告"]。



== 服务抵免额

如果瓦特/ TiB消耗量超过或不符合SLA中为某个服务级别指定的标准、NetApp将针对计费期间报告的差异为所有符合条件的订阅提供服务抵免付款。如果未满足服务级别SLA指标、请在服务月结束前一周内与NetApp全球服务支持中心(GSSC)联系确定违反服务级别后、将根据服务级别的已承诺容量计算抵免额、并在下个月的发票中记入贷方。

有关信息，请参见 link:../concepts/gssc.html["NetApp全球服务支持中心"]。
