---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: 了解 NetApp Keystone STaaS 服务版本 3 支持的存储容量类型。 
---
= Keystone 中的存储容量类型
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS 使用多个容量术语来衡量、提交和计费存储。了解这些术语将有助于您规划订阅并解读使用情况报告和发票。



== 逻辑容量

这是在应用存储阵列提供的任何数据效率之前存储用户数据所需的存储容量。



== 已提交容量

订阅期间每月支付的最低逻辑容量：

* 对于统一或块优化存储，或每个 AFF 集群，容量将分配给每个性能服务级别实例。
* 承诺容量和额外的性能服务级别可以在期限内添加。




=== 已提交容量的更改

在订阅期间，您可以根据某些条件更改承诺的容量。有关容量增加和减少规则的完整详细信息，请参阅 link:../concepts/capacity-requirements.html["Keystone性能服务级别的容量要求"]。如需请求更改，请联系您的 Keystone 成功经理 (KSM) 或 link:../concepts/support-services.html["NetApp 支持"]。



== 已用容量

消耗容量是指当前在服务上消耗的容量（以存储的 TiB 为单位）。根据数据存储类型进行不同的计算：

* *统一或块优化存储*：消耗的容量是根据订购过程中选择的容量类型（逻辑或物理）计算的。计算是按性能服务级别实例执行的。
+
.. *逻辑容量*：它是以下内容的总和：
+
*** 在存储阵列数据效率之前计量逻辑容量，用于存储所有实例和类型的客户数据，例如副本、镜像副本、版本和克隆。
*** 用于存储快照和某些克隆的元数据和差异数据的物理容量。
*** 任何厚配置的物理容量。


.. *身体能力*：它是以下各项的总和：
+
*** 在存储阵列数据效率之后，计量物理容量以存储所有实例和类型的客户数据，例如副本、镜像副本、版本和克隆。
*** 用于存储快照元数据和差异数据的物理容量。
*** 任何厚配置的物理容量。




* *AFX 存储*：按 AFX 集群计算，总和为：
+
** 在存储阵列数据效率之后，计量物理容量以存储所有实例和类型的客户数据，例如副本、镜像副本、版本和克隆。
** 用于存储快照元数据和差异数据的物理容量。
** 任何厚配置的物理容量。


* *对象存储*：已消耗容量是指用于存储所有节点上所有实例和客户数据类型的计量物理容量。此计算基于已配置的信息生命周期管理 (ILM) 策略。
* *Cloud Volumes ONTAP*：消耗的容量计算为所有 Cloud Volumes ONTAP 卷的计量配置逻辑容量。




== 突发容量

NetApp Keystone STaaS 服务允许您在承诺容量的基础上使用额外容量，以实现性能服务级别。这称为突发容量使用。

请注意以下几点：

* 突发容量限制在 Keystone 订单中约定。通常默认设置为每个性能服务级别实例或每个 AFF 集群的承诺容量之上的 20%，统一存储和块优化存储还有其他选项，可以选择承诺容量 40% 或 60% 的突发容量限制。
* 突发容量消耗按与所选数据存储类型 (DST) 和性能服务级别对应的承诺容量相同的速率开具发票。
* Keystone STaaS 服务自开始日期起提供 60 天的突发豁免期。




== 计费容量

每月账单 = （已提交容量 [TiB] * 已提交速率 [$/TiB] ） + （每日平均已配置突发容量 [TiB] * 突发速率 [$/TiB] ）。每月账单包含基于已提交容量的最低费用。

根据每日平均突发容量消耗，每月费用可能会超过最低费用。
