---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaS服务支持ONTAP和StorageGRID。 
---
= Keystone支持的存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS 服务版本 3 (v3) 支持 NetApp 和 Cloud Volumes ONTAP 的统一、块优化和对象存储。

每种存储类型包括：

* *统一存储*：包括文件、块和 S3 对象存储，可在 NetApp ONTAP AFF 和 FAS 系统上使用。
* *块优化存储*：包括 NetApp ONTAP ASA 系统上可用的块存储。
* *对象存储*：包括 NetApp StorageGRID 系统上可用的对象存储。


Keystone STaaS可为您的存储提供标准和可选服务。

* Keystone STaaS标准服务*：标准服务包含在基本订阅中、不单独收取费用。

* Keystone STaaS附加服务*：这些服务是可选的付费服务、可在标准Keystone STaaS订阅服务基础上提供额外的实用程序和优势。

Keystone STaaS 服务可以同时使用。例如，云存储订阅的期限可以与统一存储、块优化存储和对象存储订阅的期限相同。在现有存储订阅的服务期限内、可以随时包括云服务。但是，如果您不打算续订现有的统一存储、块优化存储或对象存储订阅，则在订阅的最后 90 天内无法添加云存储订阅。



== 统一、块优化和对象存储服务

Keystone STaaS 服务适用于统一存储、块优化存储和对象存储，支持多种功能和协议，如下表所述：

|===
| 存储 | 平台 | 协议 | 支持的功能 


 a| 
统一存储
 a| 
ONTAP
 a| 
NFS和CIFS
 a| 
支持所有 ONTAP One 功能



 a| 
块优化存储
 a| 
ONTAP
 a| 
FC和iSCSI
 a| 
支持所有 ONTAP One 功能



 a| 
对象存储
 a| 
StorageGRID
 a| 
S3
 a| 
支持所有 ONTAP One 功能

|===
要了解有关 ONTAP One 的更多信息，请参阅link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP许可概述"^]和link:https://www.netapp.com/blog/ontap-one/["ONTAP One：集 ONTAP 全部功能于一身"^] 。



== 云存储服务

Keystone STaaS可提供云存储服务。Keystone STaaS支持Amazon Web Services (AWS)、Microsoft Azure和Google云平台上的Cloud Volumes ONTAP 数据管理功能。


NOTE: NetApp不会在Keystone STaaS订阅中提供Cloud Volumes ONTAP 所需的基于超大规模扩展的计算、存储和网络服务；这些订阅需要直接从超大规模云服务提供商处购买。
