---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: 支持的存储容量 
---
= Keystone支持的存储容量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS服务容量包括：



== 逻辑容量

这是客户放置在Keystone基础架构上的数据。所有Keystone容量均指逻辑容量。例如、如果Keystone基础架构上存储了1 TiB文件、则应至少购买1 TiB的容量。



== 已提交容量

订阅期间每月支付的最低逻辑容量：

* 容量用于每个服务级别。
* 在此期限内、可以添加已提交的容量和其他服务级别。




=== 已提交容量的更改

在订阅期限内，您可以更改已提交的容量。但是，存在某些前提条件：

* 可根据特定条件减少已提交的容量。有关信息，请参见 link:../concepts/capacity-requirements.html["容量减少"]。
* 承诺容量不能在订阅到期前90天增加、除非订阅续订12个月。
* 您可以通过BlueXP界面或Keystone Success Manager (KSM)请求更改已提交容量。有关请求更改的信息，请参见 link:../concepts/gssc.html["NetApp全球服务支持中心"]。




== 已用容量

已用容量是指服务当前正在使用的容量(以TiB为单位)。Keystone服务会考虑特定服务级别上所有卷的逻辑已用大小(而不是已用物理容量)之和、以计算该服务级别的已用容量。



== 突发容量

超过服务级别承诺容量的任何消耗均为突发容量。


NOTE: 注意：

* Keystone服务使您可以在服务级别承诺的容量之外使用额外的容量。这是突发容量。
* 突发容量可以灵活地使用、并按消耗的平均值按日计费。
* 突发容量在Keystone协议中商定。它通常设置为比已承诺容量高出20%、并按与已承诺容量相同的速率收费。




== 计费容量

每月账单 = （已提交容量 [TiB] * 已提交速率 [$/TiB] ） + （每日平均已配置突发容量 [TiB] * 突发速率 [$/TiB] ）。每月账单包含基于已提交容量的最低费用。

根据每日平均突发容量消耗，每月费用可能会超过最低费用。
