---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: 附加、其他服务详细信息、数据分层 
---
= 数据分层
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
默认情况下、Keystone基础服务包括通过您订阅的文件和块服务进行分层的功能、这些功能可识别不太常用的数据、并将其分层到NetApp拥有、部署和管理的冷存储。如果要将冷数据分层到任何非NetApp存储、例如任何企业云存储、则可以使用分层作为附加服务。

只有在将数据分层到AWS S3、Azure Blob和EMC ECS等任何非NetApp存储时、才需要分层附加服务。

有关基础存储和云存储服务的信息、请参见 link:../concepts/supported-storage-services.html["支持的存储服务"]。

有关服务级别的信息、请参见 link:../concepts/service-levels.html["Keystone中的服务级别"]。

分层功能可利用 NetApp FabricPool 技术将数据自动分层到内部或外部的低成本对象存储层。借助此功能、不常访问的数据会根据商定的服务自动分层到内部或云中成本较低的存储中。

通过附加分层服务、可以从极高、高级、性能、标准和价值层分层到对象目标。热层和冷层会单独进行计量并开票。

可以随时添加数据分层、而不会更改定价、并且在热：冷比率方面提高了灵活性。要分层的热数据：冷数据的比率不固定、分层的物理块数是单独衡量的。

有关详细信息、请执行以下计算：

如果冷存储层的目标为：

* 价值层(高达500 TiB)、对象层(超过500 TiB)、现有SGWS网格(客户拥有)—无需额外付费；它属于基本存储服务。
* 公有 云(AWS、Azure、Google)以及任何其他第三方支持的对象存储—作为分层费用提交的数据容量需要额外付费。


附加分层订阅涉及的费用不是一次性费用。您需要在整个期限内为其付费、以保持Keystone内部文件和块服务与第三方支持的对象存储目标之间的分层关系。

此产品只能将冷数据分层到更便宜的目标存储、而不能将公有 云/超大规模基础架构成本分层。


NOTE: NetApp不会在您的Keystone订阅中提供基于超大规模云的计算和存储基础架构；您需要从超大规模云服务提供商处购买这些基础架构。
