---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: 从YUM软件存储库安装Keystone收集器软件。 
---
= 在Linux系统上安装Keystone收集器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用RPM或Debian软件包在Linux服务器上安装Keystone收集器软件。根据您的Linux版本、按照安装步骤进行操作。

[role="tabbed-block"]
====
.使用RPM
--
. 通过SSH连接到Keystone收集器服务器并升级到 `root` 权限。
. 导入Keystone公共签名：
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. 请通过检查 RPM 数据库中Keystone Billing Platform 的指纹，确保已导入正确的公共证书：
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` 正确的指纹如下所示：
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. 下载 `keystonerepo.rpm` 文件：
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. 验证文件的真实性：
`rpm --checksig -v keystonerepo.rpm` 正版文件的签名如下所示：
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. 安装YUM软件存储库文件：
`# yum install keystonerepo.rpm`
. 安装Keystone repo后、通过YUM软件包管理器安装keyston-collector软件包：
+
`# yum install keystone-collector`

+
对于 Red Hat Enterprise Linux 9，运行以下命令安装 keystone-collector 包： 
`# yum install keystone-collector-rhel9`



--
.使用Debian
--
. 通过SSH连接到Keystone收集器服务器并提升为 `root`特权。
`sudo su`
. 下载 `keystone-sw-repo.deb`文件：
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. 安装Keystone软件存储库文件：
`# dpkg -i keystone-sw-repo.deb`
. 更新软件包列表：
`# apt-get update`
. 安装Keystone repo后、安装keystone-Collector软件包：
`# apt-get install keystone-collector`


--
====

NOTE: 完成安装后、您可以使用Keystone收集器管理终端用户界面(TUI)实用程序执行配置和监控活动。您可以使用各种键盘控件(例如Enter键和箭头键)来选择选项并在此TUI中导航。请参见 link:../installation/configuration.html["配置Keystone收集器"] 和 link:../installation/monitor-health.html["监控系统运行状况"] 以了解相关信息。
