---
sidebar: sidebar 
permalink: installation/linux-prereqs.html 
keywords: prerequisites, Linux 
summary: 在Linux系统上安装Keystone收集器的前提条件 
---
= Linux系统要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在Linux系统上安装Keystone收集器需要一些配置。

Linux服务器需要以下配置：

* 操作系统：CentOS 7或Red Hat Enterprise Linux 8.6或更高版本
* 首字母缩略语时间同步
* 访问标准Linux标准软件存储库


同一台服务器还应具有以下第三方软件包：

* podman (POD管理器)
* SOS
* 按时间顺序执行
* Python 3 (3.6.8到3.9.13)


Keystone收集器服务器虚拟机(SVM)需要以下配置：

* 核心：2个CPU
* RAM：4 GB RAM
* 磁盘空间：50 GB vDisk




== 其他要求

请确保满足以下一般要求：



=== 网络要求

下表介绍了Keystone收集器的网络连接要求。


NOTE: Keystone收集器需要Internet连接。您可以通过默认网关(通过NAT)或HTTP代理直接路由来提供Internet连接。此处介绍了这两种变体。

|===


| 源 | 目标 | 服务 | 协议和端口 | 类别 | 目的 


 a| 
Keystone收集器(适用于Keystone ONTAP)
 a| 
Active IQ Unified Manager (Unified Manager)
 a| 
HTTPS
 a| 
TCP 443
 a| 
必需(如果使用Keystone ONTAP)
 a| 
ONTAP 的Keystone收集器使用情况指标收集



 a| 
Keystone收集器(适用于Keystone StorageGRID)
 a| 
StorageGRID 管理节点
 a| 
HTTPS
 a| 
TCP 443
 a| 
必需(如果使用Keystone StorageGRID)
 a| 
StorageGRID 的Keystone收集器使用情况指标收集



 a| 
Keystone收集器(通用)
 a| 
Internet (根据后面提供的URL要求)
 a| 
HTTP ， HTTPS
 a| 
TCP 80、TCP 443
 a| 
必填(Internet连接)
 a| 
Keystone收集器软件、操作系统更新和指标上传



 a| 
Keystone收集器(通用)
 a| 
客户HTTP代理
 a| 
HTTP代理
 a| 
客户代理端口
 a| 
必填(Internet连接)
 a| 
Keystone收集器软件、操作系统更新和指标上传



 a| 
Keystone收集器(通用)
 a| 
客户DNS服务器
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
必填
 a| 
DNS解析



 a| 
Keystone收集器(通用)
 a| 
客户NTP服务器
 a| 
NTP
 a| 
UDP 123
 a| 
必填
 a| 
时间同步



 a| 
Keystone收集器(适用于Keystone ONTAP)
 a| 
Unified Manager
 a| 
MySQL
 a| 
TCP 3306
 a| 
可选功能
 a| 
Keystone收集器的性能指标集合



 a| 
Keystone收集器(通用)
 a| 
客户监控系统
 a| 
HTTP
 a| 
TCP 777
 a| 
可选功能
 a| 
Keystone收集器运行状况报告



 a| 
客户的运营工作站
 a| 
Keystone收集器
 a| 
SSH
 a| 
TCP 22
 a| 
管理
 a| 
访问Keystone收集器管理



 a| 
NetApp ONTAP 集群和节点管理地址
 a| 
Keystone收集器
 a| 
http_8000、ping
 a| 
TCP 8000、ICMP回显请求/回复
 a| 
可选功能
 a| 
用于更新ONTAP 固件的Web服务器

|===


=== URL访问

Keystone收集器需要访问以下Internet主机：

|===


| Address | reason 


 a| 
https://keystone.netapp.com[]
 a| 
Keystone收集器软件更新和使用情况报告



 a| 
https://support.netapp.com[]
 a| 
NetApp总部提供计费信息和AutoSupport 交付



 a| 
https://mirror.centos.org[]
https://mirrorlist.centos.org[]
 a| 
Keystone收集器的操作系统更新(仅限OVA部署)



 a| 
http://repo.mysql.com[]
 a| 
下载并更新mysql依赖关系(仅适用于Linux部署)

|===