---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Keystone STaaS的不同版本中已修复的问题 
---
= 已修复的问题
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在NetApp Keystone STaaS服务的先前版本中发现的问题已在后续版本中得到修复。以下是修复方法。

[cols="3*"]
|===
| 问题描述 | 修复之后 | 已在版本中修复 


 a| 
如果CSV报告中的*帐户名称*列(由*容量趋势*选项卡生成)包含带逗号的帐户名称，则Keystone数据在CSV报告中放置不当 `(,)`。
 a| 
在CSV报告中已正确对齐Keystone数据。
 a| 
2024年5月29日



 a| 
从*容量趋势*选项卡中显示累积的突发使用量，即使使用量低于已提交容量也是如此。
 a| 
已修复
 a| 
2024年5月29日



 a| 
*Capacity Try*选项卡中的*Current Burst索引图标的工具提示文本不正确。
 a| 
显示正确的工具提示文本"_the ount of burst Capacity Currently Consumed.请注意、这适用于当前计费期间、而不是选定的日期范围。_"
 a| 
2024年3月28日



 a| 
如果Keystone数据在24小时内不存在、则AutoSupport订阅无法获得有关AQoS不合规卷和MetroCluster合作伙伴的信息。
 a| 
已修复
 a| 
2024年3月28日



 a| 
如果为仅满足一个服务级别的AQoS合规性的卷分配了两个服务级别，则"*卷摘要*"和"*卷详细信息*"选项卡上列出的AQoS不符合要求的卷数偶尔会不匹配。
 a| 
已修复
 a| 
2024年3月28日



 a| 
AutoSupport订阅的*Assets*选项卡上没有可用信息。
 a| 
已修复
 a| 
2024年3月14日



 a| 
如果在分层和对象存储的速率计划均适用的环境中同时启用了MetroCluster和FabricPool、则可能会错误地为镜像卷(成分卷和FabricPool卷)派生服务级别。
 a| 
已为镜像卷应用正确的服务级别。
 a| 
2024年2月29日



 a| 
对于某些订阅只有一个服务级别或速率计划，*Volumes*选项卡报告的CSV输出中缺少AQoS合规性列。
 a| 
合规性列将显示在报告中。
 a| 
2024年2月29日



 a| 
在某些MetroCluster环境中，在*Performance*选项卡的IOPS密度图表中检测到偶尔的异常。之所以出现这种情况、是因为卷与服务级别的映射不准确。
 a| 
图表已正确显示。
 a| 
2024年2月29日



 a| 
突发消耗记录的使用情况指示符显示为琥珀色。
 a| 
指示器显示为红色。
 a| 
2023年12月13日



 a| 
容量趋势、当前使用情况和性能选项卡中的日期范围和数据未转换为UTC时区。
 a| 
所有选项卡中的查询和数据的日期范围均以UTC时间(服务器时区)显示。UTC时区也会显示在选项卡上的每个日期字段的对应位置。
 a| 
2023年12月13日



 a| 
选项卡与下载的CSV报告之间的开始日期和结束日期不匹配。
 a| 
已修复。
 a| 
2023年12月13日

|===