---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: 在NetApp Keystone STaaS服务的先前版本中发现的问题已在后续版本中得到修复。 
---
= Keystone STaaS中已修复的问题
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在NetApp Keystone STaaS服务的先前版本中发现的问题已在后续版本中得到修复。

[cols="3*"]
|===
| 问题描述 | 修复之后 | 已在版本中修复 


 a| 
尽管实际使用量在允许的突发流量限制之内，Digital Advisor控制面板中订阅的显示状态错误地显示为“超出突发流量限制”。
 a| 
已修复
 a| 
2025年12月8日



 a| 
Digital Advisor仪表板中配置了MetroCluster配置的订阅的消费趋势图中缺少突发阈值线，显示不正确的 *超出突发限制* 状态。
 a| 
已修复
 a| 
2025年8月28日



 a| 
在“*Assets*”选项卡中，StorageGRID 的资产不可见。
 a| 
已修复
 a| 
2025年6月19日



 a| 
对于高级数据保护服务级别，在“消费趋势”选项卡中，图表显示了主站点和镜像站点的分割。
 a| 
图表不再显示主站点和镜像站点的分割。
 a| 
2025年6月19日



 a| 
如果使用Debian软件包安装的现有Keystone收集器尝试通过Keystone收集器管理TUI配置HTTP代理或启用Unified Manager、TUI将无响应。
 a| 
已修复
 a| 
2025年5月19日



 a| 
由于缺少通用设置、Keystone收集器for StorageGRID无法正确配置。
 a| 
已修复
 a| 
2025年5月12日



 a| 
Keystone收集器无法收集运行低于9.11版本的ONTAP集群的使用情况数据。
 a| 
已修复
 a| 
2025年4月30日



 a| 
链接订阅的使用量值显示的负数不正确、从而导致已提交的总使用量显示的值不准确。
 a| 
已修复
 a| 
2025年4月14日



 a| 
无法在*使用趋势*选项卡中查看某些订阅的服务级别的历史数据。
 a| 
已修复
 a| 
2025年4月14日



 a| 
Digital Advisor信息板上的*监视列表*中缺少*Keystone订阅*选项和*报告*中的*订阅号*选项。
 a| 
已修复
 a| 
2025年3月19日



 a| 
从Digital Advisor信息板创建或修改监视列表后、*监视列表*中缺少一些Keystone订阅。
 a| 
已修复
 a| 
2025年3月19日



 a| 
无法在*使用趋势*选项卡中查看与已过期并使用相同跟踪ID但不同服务级别续订的订阅相关的服务级别的历史数据。
 a| 
已修复
 a| 
2025年3月19日



 a| 
从*Keystone订阅*页面上的*订阅*选项卡选择超过10对 订阅时，无法生成订阅报告。
 a| 
已修复
 a| 
2025年1月8日



 a| 
无法为StorageGRID订阅加载*卷和对象*选项卡中的*卷摘要*子选项卡。
 a| 
已修复
 a| 
2024年11月21日



 a| 
导航至*消耗趋势*选项卡时，用于选择日期范围的*起始日期*字段默认显示未来日期。
 a| 
已修复
 a| 
2024年9月4日



 a| 
设置AQoS策略时、Keystone收集器管理TUI无响应。
 a| 
已修复
 a| 
2024年8月7日



 a| 
如果在*Capacity Trending*选项卡中的*Capacity Trend*选项中选择了当前日期作为上个月的开始日期和结束日期，则使用情况图表将显示指定单天时间段之外的数据。
 a| 
现在、使用情况图表可以正确显示指定单天时间段的数据。
 a| 
2024年6月27日



 a| 
对于未配置MetroCluster配置的订阅，“容量趋势”选项卡中的*CVO主*和*CVO二级*服务级别不提供历史累积突发数据。
 a| 
已修复
 a| 
2024年6月21日



 a| 
AutoSupport订阅的*卷详细信息*选项卡上列出的对象存储消耗值显示不正确。
 a| 
现在、对象存储的已用值将正确显示。
 a| 
2024年6月21日



 a| 
无法在*资产*选项卡中查看配置了MetroCluster配置的AutoSupport订阅的集群级别信息。
 a| 
已修复
 a| 
2024年6月21日



 a| 
如果CSV报告中的*帐户名称*列(由*容量趋势*选项卡生成)包含带逗号的帐户名称，则Keystone数据在CSV报告中放置不当 `(,)`。
 a| 
在CSV报告中已正确对齐Keystone数据。
 a| 
2024年5月29日



 a| 
从*容量趋势*选项卡中显示累积的突发使用量，即使使用量低于已提交容量也是如此。
 a| 
已修复
 a| 
2024年5月29日



 a| 
*Capacity Try*选项卡中的*Current Burst索引图标的工具提示文本不正确。
 a| 
显示正确的工具提示文本"_the ount of burst Capacity Currently Consumed.请注意、这适用于当前计费期间、而不是选定的日期范围。_"
 a| 
2024年3月28日



 a| 
如果Keystone数据在24小时内不存在、则AutoSupport订阅无法获得有关AQoS不合规卷和MetroCluster合作伙伴的信息。
 a| 
已修复
 a| 
2024年3月28日



 a| 
如果为仅满足一个服务级别的AQoS合规性的卷分配了两个服务级别，则"*卷摘要*"和"*卷详细信息*"选项卡上列出的AQoS不符合要求的卷数偶尔会不匹配。
 a| 
已修复
 a| 
2024年3月28日



 a| 
AutoSupport订阅的*Assets*选项卡上没有可用信息。
 a| 
已修复
 a| 
2024年3月14日



 a| 
如果在分层和对象存储的速率计划均适用的环境中同时启用了MetroCluster和FabricPool、则可能会错误地为镜像卷(成分卷和FabricPool卷)派生服务级别。
 a| 
已为镜像卷应用正确的服务级别。
 a| 
2024年2月29日



 a| 
对于某些订阅只有一个服务级别或速率计划，*Volumes*选项卡报告的CSV输出中缺少AQoS合规性列。
 a| 
合规性列将显示在报告中。
 a| 
2024年2月29日



 a| 
在某些MetroCluster环境中，在*Performance*选项卡的IOPS密度图表中检测到偶尔的异常。之所以出现这种情况、是因为卷与服务级别的映射不准确。
 a| 
图表已正确显示。
 a| 
2024年2月29日



 a| 
突发消耗记录的使用情况指示符显示为琥珀色。
 a| 
指示器显示为红色。
 a| 
2023年12月13日



 a| 
容量趋势、当前使用情况和性能选项卡中的日期范围和数据未转换为UTC时区。
 a| 
所有选项卡中的查询和数据的日期范围均以UTC时间(服务器时区)显示。UTC时区也会显示在选项卡上的每个日期字段的对应位置。
 a| 
2023年12月13日



 a| 
选项卡与下载的CSV报告之间的开始日期和结束日期不匹配。
 a| 
已修复。
 a| 
2023年12月13日

|===