---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaS的新增功能和增强功能。 
---
= Keystone STaaS的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp在每个Keystone STaaS服务版本中都为您提供新增和增强功能。



== 2024年2月29日的新增功能和增强功能

此版本的Active IQ数字顾问(也称为数字顾问)信息板和*Keystone订阅*屏幕上进行了多项增强：



=== 新增了"Assets"(资产)选项卡

Keystone订阅*屏幕现在包括*Assets*选项卡。此新选项卡可根据您的订阅提供集群级别的信息。有关详细信息，请参见 link:../integrations/assets-tab.html["资产选项卡"^]。



=== 改进了卷和对象选项卡

为使ONTAP系统卷更加清晰，在*Volumes*选项卡中添加了两个新的选项卡按钮：*卷摘要*和*卷详细信息*。"*卷摘要*"选项卡提供与您订阅的服务级别关联的卷的总数，包括其AQoS合规状态和容量信息。“*卷详细信息*”选项卡列出了所有卷及其具体信息。有关详细信息，请参见 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。



=== 增强了Digital Advisor的搜索体验

现在，*Digital Advisor屏幕上的搜索参数包括Keystone订阅号码和为Keystone订阅创建的监视列表。您可以输入订阅编号或监视列表名称的前三个字符。有关详细信息，请参见 link:../integrations/keystone-aiq.html["在Active IQ数字顾问上查看Keystone信息板"^]。



=== 查看消耗数据的时间戳

您可以在*Keystone订阅*小工具的旧信息板上查看消耗数据的时间戳(UTC)。



== 2024年2月13日的新增功能和增强功能

Active IQ数字顾问(也称为数字顾问)的*Keystone订阅*屏幕进行了以下增强。



=== 能够查看与主订阅关联的订阅

您的某些主要订阅可以具有链接的二级订阅。在这种情况下，主订阅号将继续显示在*订阅号*列中，而链接的订阅号将在*订阅*选项卡上的新列*链接订阅*中列出。只有当您有链接订阅时，*链接的订阅*列才对您可用，并且您可以看到有关这些订阅的信息消息。



== 2024年1月11日的新增功能和增强功能

了解此版本中的新增功能。

Active IQ数字顾问(也称为数字顾问)的*Keystone订阅*屏幕具有以下增强功能。



=== 针对累积突发返回的发票数据

现在，*容量趋势*选项卡中的*应计突发*标签已修改为*已发票应计突发*。选择此选项可查看计费累积突发数据的月度图表。有关详细信息，请参见 link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["查看已开票的应计突发量"^]。



=== 特定费率计划的应计消费详细信息

如果您的订阅包含已提交容量为_zero_的费率计划、则可以在*容量趋势*选项卡中查看累积消耗详细信息。选择“*开票应计消费*”选项后，您可以查看开票应计消费数据的月度图表。



== 2023年12月15日的新增功能和增强功能

了解此版本中的新增功能。



=== 可以按监视列表进行搜索

Active IQ数字顾问(也称为数字顾问)中对监视列表的支持已扩展到包括Keystone系统。现在、您可以通过使用监视列表进行搜索来查看多个客户的订阅详细信息。有关在Keystone STaaS中使用监视列表的详细信息、请参见 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["使用Keystone监视列表进行搜索"^]。



=== 转换为UTC时区的日期

在Active IQ数字顾问的*Keystone订阅*屏幕的选项卡上返回的数据以UTC时间(服务器时区)显示。输入查询日期时、系统会自动将其视为UTC时间。有关详细信息，请参见 link:../integrations/aiq-keystone-details.html["Keystone订阅信息板和报告"^]。
