---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp在每个Keystone STaaS服务版本中都为您提供新增和增强功能。 
---
= Keystone STaaS的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp在每个Keystone STaaS服务版本中都为您提供新增和增强功能。



== 2025年6月30日

您现在可以订阅 Keystone 版本 3 (v3)，这是 NetApp Keystone STaaS 产品的最新版本。此版本引入了多项增强功能，包括简化的性能服务级别、额外的突发容量选项以及灵活的计费频率。这些改进简化了存储解决方案的管理、优化和扩展。要了解更多信息，请参阅 link:../concepts/metrics.html["v3 的 Keystone STaaS 服务"]。



== 2025年6月19日



=== BlueXP 中的 Keystone 仪表板

您现在可以直接从 BlueXP 访问 Keystone 仪表板。此集成让您可以在一个位置监控、管理和跟踪所有 Keystone 订阅以及其他 NetApp 服务。

使用 BlueXP 中的 Keystone 仪表板，您可以：

* 在一个地方查看所有订阅详细信息、容量使用情况和资产。
* 轻松管理订阅并随着需求的变化请求更改。
* 随时了解有关您的存储环境的最新信息。


首先，转到 BlueXP 左侧导航菜单中的 *存储 > Keystone*。要了解更多信息，请参阅 link:../integrations/dashboard-overview.html["Keystone信息板概述"]。



== 2025年1月8日



=== 增加了每日累积数据使用量查看选项

现在、您可以通过单击显示发票数据的条形来以图形或表格形式查看每月或每季度计费期间的每日累积突发数据使用量。要了解更多信息，请参阅 link:../integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["查看每日累积突发数据使用量"]。



== 2024年12月12日



=== 已重命名逻辑使用量列

现在，*卷和对象*中的*卷详细信息*选项卡中的*逻辑使用量*列已重命名为* Keystone逻辑使用量*。



=== 增强型资产选项卡

现在，*Keystone订阅*屏幕中的*Assets*选项卡有两个新的子选项卡：* ONTAP *和* StorageGRID *。这些子选项卡可根据您的订阅提供有关ONTAP的集群级详细见解以及有关StorageGRID的网格级信息。要了解更多信息，请参阅 link:../integrations/assets-tab.html["资产选项卡"^]。



=== 新增隐藏/显示列选项

现在，*Volumes & Objects*中的*Volume Details*选项卡包含*Hide/Show Column*选项。使用此选项可以选择或取消选择列、以便根据您的首选项自定义卷的表格列表。要了解更多信息，请参阅 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。



== 2024年11月21日



=== 增加了开票应计突发量

现在，如果您选择了季度计费期，则可以通过*开票应计突发*选项按季度查看累积突发使用情况数据。要了解更多信息，请参阅 link:../integrations/consumption-tab.html#view-accrued-burst["查看已开票的应计突发量"^]。



=== 卷详细信息选项卡中的新列

为了更清楚地计算逻辑使用量，在*卷和对象*选项卡的*卷详细信息*选项卡中增加了两个新列：

* *逻辑AFS*：显示卷的活动文件系统使用的逻辑容量。
* *物理快照*：显示快照使用的物理空间。


这些列可以更清楚地显示*逻辑使用量*列、该列显示卷的活动文件系统使用的逻辑容量与快照使用的物理空间之和。



== 2024年11月11日



=== 增强了报告生成功能

现在、您可以使用Digital Advisor中的"报告"功能生成整合报告以查看Keystone数据的详细信息。要了解更多信息，请参阅link:../integrations/options.html#generate-consolidated-report-from-digital-advisor["生成整合报告"^] 。



== 2024年7月10日



=== 标签修改

标签*Current Usage*将更改为*Current功耗*，*Capacity Try*将更改为*功 耗趋势*。



=== 订阅的搜索栏

Keystone订阅*屏幕中所有选项卡上的*订阅*下拉菜单现在包含一个搜索栏。您可以搜索*订阅*下拉列表中列出的特定订阅。



== 2024年6月27日



=== 一致的订阅显示

Keystone订阅*屏幕已更新，可在所有选项卡中显示选定的订阅编号。

* 刷新*Keystone订阅*屏幕中的任何选项卡后，屏幕将自动导航到*订 阅*选项卡，并将所有选项卡重置为*订 阅*下拉列表中列出的第一个订阅。
* 如果选定订阅未订阅性能指标，*性能*选项卡将在导航时显示*订阅*下拉列表中列出的第一个订阅。




== 2024年5月29日



=== 增强型突发指示器

使用情况图索引中的*突发*指示器已增强，可显示突发限制百分比值。此值会根据订阅的约定突发限制而变化。您还可以通过将鼠标悬停在*使用状态*列中的*突发使用情况*指示符上方，在*订阅*选项卡中查看突发限制值。



=== 添加服务级别

包含服务级别*CVO主*和*CVO二级*，以支持Cloud Volumes ONTAP订阅，这些订阅的费率计划中的已承诺容量为零，或者配置了城域群集。

* 您可以从*Keystone订阅*小工具的旧信息板和*Capacity Try*选项卡查看这些服务级别的容量使用情况图，还可以从*Current Usage*选项卡查看详细的使用情况信息。
* 在*订阅*选项卡中，这些服务级别显示为 `CVO (v2)` 在*使用类型*列中，允许根据这些服务级别标识计费。




=== 用于短期突发的放大功能

现在，“*容量趋势*”选项卡包含一个放大功能，用于在使用情况图表中查看短期突发的详细信息。有关详细信息，请参见 link:../integrations/consumption-tab.html["容量趋势选项卡"^]。



=== 增强了订阅显示功能

订阅的默认显示已增强、可按跟踪ID排序。现在，*订阅*选项卡(包括*订阅*下拉列表和CSV报告)中的订阅将按跟踪ID的字母顺序显示，顺序依次为a、a、b、B等。



=== 增强的累积突发显示

现在，将鼠标悬停在“*容量趋势”选项卡中的容量使用情况条形图上时显示的工具提示将根据已提交容量显示应计突发的类型。它区分临时突发和开票突发、对于承诺容量为零的订阅、显示*临时应计量*和*开票应计量*；对于承诺容量不为零的订阅、显示*临时应计突发*和*开票应计突发*。



== 2024年5月9日



=== CSV报告中的新列

现在，“*容量趋势*”选项卡中的CSV报告包括“*订阅号*”和“*帐户名称*”列，以改进详细信息。



=== 增强型使用类型列

*订阅*选项卡中的*使用类型*列已得到增强，可将逻辑和物理使用显示为包含文件和对象服务级别的订阅的逗号分隔值。



=== 从卷详细信息选项卡访问对象存储详细信息

现在，*卷和对象*选项卡中的*卷详细信息*选项卡可提供对象存储详细信息以及包含文件和对象服务级别的订阅的卷信息。您可以单击*卷详细信息*选项卡中的*对象存储详细信息*按钮来查看详细信息。



== 2024年3月28日



=== 在"Volume Details"(卷详细信息)选项卡中显示对QoS策略合规性的改进

现在，可以通过*卷和对象*选项卡中的*卷详细信息*选项卡更好地了解服务质量(QoS)策略合规性。以前称为*AQOs*的列已重命名为*符合*，表示QoS策略是否符合。此外，还添加了一个新列*QoS策略类型*，用于指定策略是固定策略还是自适应策略。如果这两种情况都不适用、则该列将显示_not available _。有关详细信息，请参见 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。



=== 卷摘要选项卡中显示新列和简化的订阅

* 现在，“*卷和对象*”选项卡中的“*卷摘要*”选项卡包含一个标题为“*受保护*”的新列。此列提供与您订阅的服务级别关联的受保护卷的计数。如果单击受保护卷的数量，则会转到*卷详细信息*选项卡，在此可以查看经过筛选的受保护卷列表。
* *卷摘要*选项卡已更新，仅显示基础订阅，不包括附加服务。有关详细信息，请参见 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。




=== 更改为容量趋势选项卡中的应计突发详细信息显示

将鼠标悬停在*容量趋势*选项卡中的容量使用情况条形图上时显示的工具提示将显示当月累积突发的详细信息。我们将不提供前几个月的详细信息。



=== 增强了查看Keystone订阅历史数据的访问权限

现在、如果修改或续订了Keystone订阅、您可以查看历史数据。您可以将订阅的开始日期设置为以前的日期以查看：

* 来自“容量趋势”选项卡的消耗和累计突发使用数据。
* “性能”选项卡中的 ONTAP 卷的性能指标。


数据根据所选的订阅开始日期显示。



== 2024年2月29日



=== 新增了"Assets"(资产)选项卡

Keystone订阅*屏幕现在包括*Assets*选项卡。此新选项卡可根据您的订阅提供集群级别的信息。有关详细信息，请参见 link:../integrations/assets-tab.html["资产选项卡"^]。



=== 改进了卷和对象选项卡

为使ONTAP系统卷更加清晰，在*Volumes*选项卡中添加了两个新的选项卡按钮：*卷摘要*和*卷详细信息*。"*卷摘要*"选项卡提供与您订阅的服务级别关联的卷的总数，包括其AQoS合规状态和容量信息。“*卷详细信息*”选项卡列出了所有卷及其具体信息。有关详细信息，请参见 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。



=== 增强了Digital Advisor的搜索体验

现在，*Digital Advisor屏幕上的搜索参数包括Keystone订阅号码和为Keystone订阅创建的监视列表。您可以输入订阅编号或监视列表名称的前三个字符。有关详细信息，请参见 link:../integrations/keystone-aiq.html["在 Active IQ Digital Advisor 上查看 Keystone 仪表板"^]。



=== 查看消耗数据的时间戳

您可以在*Keystone订阅*小工具的旧信息板上查看消耗数据的时间戳(UTC)。



== 2024年2月13日



=== 能够查看与主订阅关联的订阅

您的某些主要订阅可以具有链接的二级订阅。在这种情况下，主订阅号将继续显示在*订阅号*列中，而链接的订阅号将在*订阅*选项卡上的新列*链接订阅*中列出。只有当您有链接订阅时，*链接的订阅*列才对您可用，并且您可以看到有关这些订阅的信息消息。



== 2024年1月11日



=== 针对累积突发返回的发票数据

现在，*容量趋势*选项卡中的*应计突发*标签已修改为*已发票应计突发*。选择此选项可查看计费累积突发数据的月度图表。有关详细信息，请参见 link:../integrations/consumption-tab.html#view-accrued-burst["查看已开票的应计突发量"^]。



=== 特定费率计划的应计消费详细信息

如果您的订阅包含已提交容量为_zero_的费率计划、则可以在*容量趋势*选项卡中查看累积消耗详细信息。选择“*开票应计消费*”选项后，您可以查看开票应计消费数据的月度图表。



== 2023年12月15日



=== 可以按监视列表进行搜索

Digital Advisor中对监视列表的支持已扩展到包括Keystone系统。现在、您可以通过使用监视列表进行搜索来查看多个客户的订阅详细信息。有关在Keystone STaaS中使用监视列表的详细信息，请参见 link:../integrations/keystone-aiq.html#search-by-keystone-watchlists["按Keystone监视列表搜索"^]。



=== 转换为UTC时区的日期

Digital Advisor 的 *Keystone Subscriptions* 屏幕选项卡上返回的数据以 UTC 时间（服务器时区）显示。输入查询日期时、系统会自动将其视为UTC时间。有关详细信息，请参见 link:../integrations/keystone-aiq.html["Keystone订阅信息板和报告"^]。
