---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaS的新增功能和增强功能。 
---
= Keystone STaaS的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp在每个Keystone STaaS服务版本中都为您提供新增和增强功能。

Active IQ数字顾问(也称为数字顾问)的*Keystone订阅*屏幕中引入了以下增强功能：



== 2024年5月29日



=== 增强型突发指示器

使用情况图索引中的*突发*指示器已增强，可显示突发限制百分比值。此值会根据订阅的约定突发限制而变化。您还可以通过将鼠标悬停在*使用状态*列中的*突发使用情况*指示符上方，在*订阅*选项卡中查看突发限制值。



=== 添加服务级别

包含服务级别*CVO主*和*CVO二级*，以支持Cloud Volumes ONTAP订阅，这些订阅的费率计划中的已承诺容量为零，或者配置了城域群集。

* 您可以从*Keystone订阅*小工具的旧信息板和*Capacity Try*选项卡查看这些服务级别的容量使用情况图，还可以从*Current Usage*选项卡查看详细的使用情况信息。
* 在*订阅*选项卡中，这些服务级别显示为 `CVO (v2)` 在*使用类型*列中，允许根据这些服务级别标识计费。




=== 放大功能、可提供微爆发洞察力

现在，*容量趋势*选项卡包含一个放大功能，可用于在使用情况图表中查看短期浪涌(称为微爆发)的详细信息。有关详细信息，请参见 link:../integrations/capacity-trend-tab.html["容量趋势选项卡"^]。



=== 增强了订阅显示功能

订阅的默认显示已增强、可按跟踪ID排序。现在，*订阅*选项卡(包括*订阅*下拉列表和CSV报告)中的订阅将根据跟踪ID的字母顺序显示，顺序依次为a、a、b、B等。



=== 增强的累积突发显示

现在，将鼠标悬停在“*容量趋势”选项卡中的容量使用情况条形图上时显示的工具提示将根据已提交容量显示应计突发的类型。它区分临时突发和开票突发、对于承诺容量为零的订阅、显示*临时应计量*和*开票应计量*；对于承诺容量不为零的订阅、显示*临时应计突发*和*开票应计突发*。



== 2024年5月9日



=== CSV报告中的新列

现在，“*容量趋势*”选项卡中的CSV报告包括“*订阅号*”和“*帐户名称*”列，以改进详细信息。



=== 增强型使用类型列

*订阅*选项卡中的*使用类型*列已得到增强，可将逻辑和物理使用显示为包含文件和对象服务级别的订阅的逗号分隔值。



=== 从卷详细信息选项卡访问对象存储详细信息

现在，*卷和对象*选项卡中的*卷详细信息*选项卡可提供对象存储详细信息以及包含文件和对象服务级别的订阅的卷信息。您可以单击*卷详细信息*选项卡中的*对象存储详细信息*按钮来查看详细信息。



== 2024年3月28日



=== 在"Volume Details"(卷详细信息)选项卡中显示对QoS策略合规性的改进

现在，可以通过*卷和对象*选项卡中的*卷详细信息*选项卡更好地了解服务质量(QoS)策略合规性。以前称为*AQOs*的列已重命名为*符合*，表示QoS策略是否符合。此外，还添加了一个新列*QoS策略类型*，用于指定策略是固定策略还是自适应策略。如果这两种情况都不适用、则该列将显示_not available _。有关详细信息，请参见 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。



=== 卷摘要选项卡中显示新列和简化的订阅

* 现在，“*卷和对象*”选项卡中的“*卷摘要*”选项卡包含一个标题为“*受保护*”的新列。此列提供与您订阅的服务级别关联的受保护卷的计数。如果单击受保护卷的数量，则会转到*卷详细信息*选项卡，在此可以查看经过筛选的受保护卷列表。
* *卷摘要*选项卡已更新，仅显示基础订阅，不包括附加服务。有关详细信息，请参见 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。




=== 更改为容量趋势选项卡中的应计突发详细信息显示

将鼠标悬停在*容量趋势*选项卡中的容量使用情况条形图上时显示的工具提示将显示当月累积突发的详细信息。我们将不提供前几个月的详细信息。



=== 增强了查看Keystone订阅历史数据的访问权限

现在、如果修改或续订了Keystone订阅、您可以查看历史数据。您可以将订阅的开始日期设置为以前的日期以查看：

* *容量趋势*选项卡中的消耗量和累积突发使用量数据，
* 通过*性能*选项卡查看ONTAP卷的性能指标。


所有这些内容均基于选定订阅日期显示数据。



== 2024年2月29日的新增功能和增强功能

此版本的Active IQ数字顾问(也称为数字顾问)信息板和*Keystone订阅*屏幕上进行了多项增强：



=== 新增了"Assets"(资产)选项卡

Keystone订阅*屏幕现在包括*Assets*选项卡。此新选项卡可根据您的订阅提供集群级别的信息。有关详细信息，请参见 link:../integrations/assets-tab.html["资产选项卡"^]。



=== 改进了卷和对象选项卡

为使ONTAP系统卷更加清晰，在*Volumes*选项卡中添加了两个新的选项卡按钮：*卷摘要*和*卷详细信息*。"*卷摘要*"选项卡提供与您订阅的服务级别关联的卷的总数，包括其AQoS合规状态和容量信息。“*卷详细信息*”选项卡列出了所有卷及其具体信息。有关详细信息，请参见 link:../integrations/volumes-objects-tab.html["卷和对象选项卡()"^]。



=== 增强了Digital Advisor的搜索体验

现在，*Digital Advisor屏幕上的搜索参数包括Keystone订阅号码和为Keystone订阅创建的监视列表。您可以输入订阅编号或监视列表名称的前三个字符。有关详细信息，请参见 link:../integrations/keystone-aiq.html["在Active IQ数字顾问上查看Keystone信息板"^]。



=== 查看消耗数据的时间戳

您可以在*Keystone订阅*小工具的旧信息板上查看消耗数据的时间戳(UTC)。



== 2024年2月13日



=== 能够查看与主订阅关联的订阅

您的某些主要订阅可以具有链接的二级订阅。在这种情况下，主订阅号将继续显示在*订阅号*列中，而链接的订阅号将在*订阅*选项卡上的新列*链接订阅*中列出。只有当您有链接订阅时，*链接的订阅*列才对您可用，并且您可以看到有关这些订阅的信息消息。



== 2024年1月11日



=== 针对累积突发返回的发票数据

现在，*容量趋势*选项卡中的*应计突发*标签已修改为*已发票应计突发*。选择此选项可查看计费累积突发数据的月度图表。有关详细信息，请参见 link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["查看已开票的应计突发量"^]。



=== 特定费率计划的应计消费详细信息

如果您的订阅包含已提交容量为_zero_的费率计划、则可以在*容量趋势*选项卡中查看累积消耗详细信息。选择“*开票应计消费*”选项后，您可以查看开票应计消费数据的月度图表。



== 2023年12月15日



=== 可以按监视列表进行搜索

Active IQ数字顾问(也称为数字顾问)中对监视列表的支持已扩展到包括Keystone系统。现在、您可以通过使用监视列表进行搜索来查看多个客户的订阅详细信息。有关在Keystone STaaS中使用监视列表的详细信息、请参见 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["使用Keystone监视列表进行搜索"^]。



=== 转换为UTC时区的日期

在Active IQ数字顾问的*Keystone订阅*屏幕的选项卡上返回的数据以UTC时间(服务器时区)显示。输入查询日期时、系统会自动将其视为UTC时间。有关详细信息，请参见 link:../integrations/aiq-keystone-details.html["Keystone订阅信息板和报告"^]。
